//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietaryRequirement
    {
        public DietaryRequirement()
        {
            this.IngredientDietaryRequirements = new HashSet<IngredientDietaryRequirement>();
        }
    
        public int DietaryRequirementID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<IngredientDietaryRequirement> IngredientDietaryRequirements { get; set; }
    }
}
