//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientDietaryRequirement
    {
        public int IngredientDietaryRequirementID { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public Nullable<int> DietaryRequirementID { get; set; }
    
        public virtual DietaryRequirement DietaryRequirement { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
