//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Instructions = new HashSet<Instruction>();
            this.RecipeEquipments = new HashSet<RecipeEquipment>();
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int RecipeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MealType { get; set; }
        public int PreparationTime { get; set; }
        public int CookTime { get; set; }
        public int NumberOfServings { get; set; }
        public string Author { get; set; }
    
        public virtual ICollection<Instruction> Instructions { get; set; }
        public virtual ICollection<RecipeEquipment> RecipeEquipments { get; set; }
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}
