// <auto-generated />
namespace RecipeAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Make_FK_relationships_of_instructions_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_FK_relationships_of_instructions_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201507312328138_Make_FK_relationships_of_instructions_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
