// <auto-generated />
namespace RecipeAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addimagesourcetorecipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addimagesourcetorecipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201512301712380_Add-image-source-to-recipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
